version: "3.8"
services:
  mysql:
    container_name: "database"
    image: mysql:8.0
    volumes:
      - ftg-mysql-data:/var/lib/mysql
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - ftg-network
  fungalf-the-grey:
    container_name: "bot"
    build: .
    env_file:
      - .env
    networks:
      - ftg-network
    stop_signal: SIGTERM
volumes:
  ftg-mysql-data:
networks:
  ftg-network:
